# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 一顆藍莓
subtitle: 喜歡做奇怪東西的前端工程師
description: 喜歡做奇怪東西的前端工程師
keywords: Javascript, Angular, React, Node.js, MySQL, Figma, UI, 爬蟲, Discord Bot
author: Blueberry
language: zh-TW
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://b-l-u-e-b-e-r-r-y.github.io/
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: /source/google0cc10fba780cd465.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
    enable: true
    line_number: true
    auto_detect: true
    tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
    path: ''
    per_page: 10
    order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: book

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
    type: git
    repo: git@github.com:B-l-u-e-b-e-r-r-y/B-l-u-e-b-e-r-r-y.github.io.git #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
    branch: master #published
    message: #leave this blank

archive_generator:
    per_page: 0
    yearly: false
    monthly: false
    daily: false

# Social Accounts
twitter:
rss:
weibo:
instagram:
github: https://github.com/B-l-u-e-b-e-r-r-y
facebook:

# Comment
duoshuo:
disqus:
gentie:
# Valine comments https://valine.js.org
valine:
    enable: false # if you want use valine, please set enable: true
    appid: # your leancloud appid
    appkey: # your leancloud appkey
    notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
    verify: false # true/false:verify code
    avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
    placeholder: Just go go # comment box placeholder

#Sitemap
sitemap:
    path: sitemap.xml

markdown:
    render:
        html: true # Doesn't escape HTML content so the tags will appear as html.
        xhtmlOut: false # Parser will not produce XHTML compliant code.
        breaks: true # Parser produces `<br>` tags every time there is a line break in the source document.
        linkify: true # Returns text links as text.
        typographer: true # Substitution of common typographical elements will take place.
        quotes:
            '“”‘’' # "double" will be turned into “single”
            # 'single' will be turned into ‘single’
    plugins:
        - markdown-it-abbr
        - markdown-it-container
        - markdown-it-deflist
        - markdown-it-emoji
        - markdown-it-footnote
        - markdown-it-imsize
        - markdown-it-ins
        - markdown-it-mark
        - markdown-it-regexp
        - markdown-it-sub
        - markdown-it-sup
        - markdown-it-checkbox
        - name: markdown-it-container
          options: note
        - name: markdown-it-container
          options: tip
        - name: markdown-it-container
          options: attention
    anchors:
        # Minimum level for ID creation. (Ex. h2 to h6)
        level: 1
        # A suffix that is prepended to the number given if the ID is repeated.
        collisionSuffix: 'v'
        # If `true`, creates an anchor tag with a permalink besides the heading.
        permalink: false
        # Class used for the permalink anchor tag.
        permalinkClass: header-anchor
        # The symbol used to make the permalink
        permalinkSymbol: '# '